add Z-index on header
WildCodeSchool/orleans-js-0920-p2-hero-training pull request #56
Opened 2020-11-16 11:28 UTC by FlorianBEME

2020-11-16 11:29 UTC, ManuelWCS approved these changes

2020-11-16 14:50 UTC, ldupas requested changes

2020-11-16 14:50 UTC, ldupas commented on src/components/header/Header.css
> +  z-index: 100;
éviter les trop gros nombres pour les z-index (1, 2, 3, etc largement suffisant)

2020-11-18 07:26 UTC, ldupas approved these changes

2020-11-18 07:26 UTC, merged