add feature + css
WildCodeSchool/orleans-js-0920-p2-hero-training pull request #62
Opened 2020-11-18 15:10 UTC by FlorianBEME

2020-11-18 15:11 UTC, ManuelWCS approved these changes
carré

2020-11-23 08:17 UTC, ManuelWCS approved these changes

2020-11-23 08:48 UTC, ldupas requested changes

2020-11-23 08:48 UTC, ldupas commented on src/components/hero/Hero.jsx
> +                  <label for="force">Force : </label>
strength ?

2020-11-23 08:48 UTC, ldupas commented on src/components/hero/Hero.css
> +.loadingPage {
un saut à la ligne entre chaque sélecteur pour aérer le fichier

2020-11-23 13:34 UTC, ldupas approved these changes

2020-11-23 13:34 UTC, merged